version: '3.7'

services:
  jupyter:
    restart: always
    build:
      context: .
      dockerfile: python3-jupyter.dockerfile
    image: jupyter
    ports:
      - "8888:8888"
    volumes:
      - type: bind
        source: "C:/Users/duoqu"
        target: /app
    